### ISSUE TITLE
clarity on (Id10273) Did the baby stop suckling?, its causing confusion for interviwers

### ISSUE THREAD

**Issue by QollinsOchieng** [SwissTPH/WHO_VA_2016#46] opened 2019-05-10 09:02 UTC
(Id10273) Did the baby stop suckling?
This question is causing confusion during data collection. In the sense that it is mistaken to mean when the baby stopped breastfeeding. Alot of responses sent through VA denotes duration of baby stopping to breastfeed which is normal. Please update Q by Q and also add hint or rephrase the question to collect accurate data on this.

**Comment by aurdipas** [comment] 2019-05-10 09:09
duplicate of #45

**Closed by aurdipas** 2019-05-10 09:09 UTC
Labels: duplicate
